### ISSUE TITLE
How can I use this image with B2?

### ISSUE THREAD

**Issue by jwillmer** [instrumentisto/restic-docker-image#2]
I search for an image that supports [B2 cloud storage](https://www.backblaze.com/b2/cloud-storage.html) and has a cron job included. Does that image support this? The documentation is somewhat limited.

**Comment by tyranron** [comment]
@jwillmer did you try following [instructions from restic documentation](http://restic.readthedocs.io/en/v0.9.0/030_preparing_a_new_repo.html#backblaze-b2), but replace raw `restic` command with Docker-wrapped one?

**Comment by jwillmer** [comment]
I didn't follow any instructions since I would like to have a docker image that I can setup with a docker-compose file there I set the environment variables. But in `How to use this image` I only see commands for `AWS`.

**Comment by tyranron** [comment]
@jwillmer yup, the `How to use this image` section provides general idea of using this Docker image, not solutions for every single case. You need to combine that general idea with arguments/env vars required for your specific case. All possible arguments are described well in official restic documentation: [restic.readthedocs.io](http://restic.readthedocs.io).

I suppose it will be something like this:
```bash
docker run --rm -v "$(pwd)":/data \
           -e RESTIC_REPOSITORY=b2:bucketname:path/to/repo \
           -e RESTIC_PASSWORD=my-secure-password \
           -e B2_ACCOUNT_ID=my-account-id \
           -e B2_ACCOUNT_KEY=my-secret-account-key \
    instrumentisto/restic init

docker run --rm -v "$(pwd)":/data \
           -e RESTIC_REPOSITORY=b2:bucketname:path/to/repo \
           -e RESTIC_PASSWORD=my-secure-password \
           -e B2_ACCOUNT_ID=my-account-id \
           -e B2_ACCOUNT_KEY=my-secret-account-key \
    instrumentisto/restic backup /data
```

I won't recommend to use Docker Compose, since this image does not provide any long-running services. It's just command-line tool, so raw Docker CLI is more than enough.

If you wish to run backup periodically - make an appropriate `cron` job which runs `backup` command above.

**Comment by jwillmer** [comment]
Ah O.K., I thought there would be a `cron` job inside the image already. Why do you define the `data` direction in both commands, isn't it enough to use it as last argument for starting a backup?

**Comment by tyranron** [comment]
@jwillmer actually, an image is based on `alpine` which has `crond`:
So, you can mount `/etc/crontab` and use `--entrypoint crond`. But I won't recommend that. It's better to be controlled from outside.

> Why do you define the data direction in both commands, isn't it enough to use it as last argument for starting a backup?

On your choice 😉
